### PR TITLE
update coach to latest

### PR DESCRIPTION
**Pull request by pandafulmanda**
pulls in latest [coach updates](https://github.com/openstax/tutor-js/releases/tag/coach-20161221.a)

needs #1476 to not fail travis

### CODE REVIEW

**Comment by RoyEJohnson** [comment]
Travis is refusing to build.

**Comment by pandafulmanda** [comment]
yes @RoyEJohnson that's because #1476 is needed

**Comment by RoyEJohnson** [comment]
Half better.

  1) backbone history helper tests "before each" hook:
     Uncaught Error: Script error for: coffee-script
http://requirejs.org/docs/errors.html#scripterror (file:///home/travis/build/Connexions/webview/bower_components/requirejs/require.js:140)

**Comment by pandafulmanda** [comment]
The PR travis one passes because the needed fix is in the version of this merged to master.  However, this push alone/the travis build off of this branch off of master before #1476 doesn't work, as expected.

**Comment by RoyEJohnson** [comment]
That would make me feel better, because I don't really understand what's going on. I don't have a problem with the code update itself, obviously.

**Pull request merged**
