### PR TITLE
Retain teacher edition state between pages

### LINKED ISSUE #945: Teacher's Edition content does not show when navigating page to page
1. contents/26ecc5de-5436-4ab8-b305-620542bc484d@1.1:1/Updated_Tutor_HS_Physics_Test_
2. Toggle teacher's edition in tools
3. Navigate to next page which also has teacher's edition content. This page does not show teacher's edition even though the link is toggled.

### PR DESCRIPTION
**Pull request by dak**
Fixes #945

### CODE REVIEW

**Comment by amberwebb** [comment]
I tested this with /contents/26ecc5de-5436-4ab8-b305-620542bc484d@1.1:1/Updated_Tutor_HS_Physics_Test_

1. While on page 1, click teacher's edition toggle.
2. Click next to go to page 2.

Teacher's edition content on page 2 does not show until you click 'Standard Edition' and then 'Teacher's Edition' again.

Also have error in console:
Error: Syntax error, unrecognized expression: #ost/api/ex/k12phys-ch04-ex001 {stack: (...), message: "Syntax error, unrecognized expression: #ost/api/ex/k12phys-ch04-ex001"}

**Comment by reedstrm** [comment]
so, doesn't work, then?

**Comment by dak** [comment]
@reedstrm: There's a bug when navigating back to an already loaded page (it works when navigating to a new page that hasn't loaded).  Working on a fix.

**Comment by dak** [comment]
@reedstrm: There's a bug when navigating back to an already loaded page (it works when navigating to a new page that hasn't loaded).  Working on a fix.

**Comment by dak** [comment]
@reedstrm: There's a bug when navigating back to an already loaded page (it works when navigating to a new page that hasn't loaded).  Working on a fix.

**Pull request merged**
