### PR TITLE
only style the raw lists

### PR DESCRIPTION
**Pull request by philschatz**
baked content has the characters baked in so this is not needed

### CODE REVIEW

**Comment by philschatz** [comment]
@kerwinso Can you send a link to content that contains these double-semicolons in lists? tea or qa or wherever is fine.

**Comment by kerwinso** [comment]
@philschatz Here's a couple:
https://tea.cnx.org/contents/sSWElGPd@5.209:fG2Thad5@7/11-Definitions-of-Statistics-P

https://tea.cnx.org/contents/sSWElGPd@5.209:2mxXJYjP@5/26-Skewness-and-the-Mean-Media

**Comment by philschatz** [comment]
ok, it seems to work. Here is a screenshot:

image

I'm not sure who should review the code though so I'll just assign it to `@kerwinso`

**Comment by helenemccarron** [comment]
It's really nice to be able to simply move all of it into the raw css, so easy!

**Comment by kerwinso** [comment]
@philschatz I don't think I should be the one to review the code itself. As for testing, I can help out with that, but I will need more specific guidance as my brain is currently melting. Thanks!

**Comment by philschatz** [comment]
I think the test should be:

- verify there is only one semicolon in the baked content. [Example](https://tea.cnx.org/contents/sSWElGPd@5.209:fG2Thad5@7/11-Definitions-of-Statistics-P)
- verify there is only one semicolon in the raw content. [Example](https://tea.cnx.org/contents/fG2Thad5@7/11-Definitions-of-Statistics-P)
- check that blockish lists (not _inline_) that have different attributes still work in the Raw HTML. maybe search for: 

  - `/xpath?q=c:list[@bullet-style='pilcrow']`
  - `/xpath?q=c:list[@number-style='upper-roman']`
  - `/xpath?q=c:list[@start-value]`
  - `/xpath?q=c:list[@mark-prefix]`
  - `/xpath?q=c:list[@mark-suffix]`
  - `/xpath?q=c:list[@item-sep]`
  - `/xpath?q=c:list[c:title]`

- and some more inline-list fodder (optional 😄 )
  - `/xpath?q=c:para//c:list[@bullet-style or @number-style or @start-value or @mark-prefix or @mark-suffix or @item-sep or c:title]`
  - `/xpath?q=c:list[@display='inline'][@bullet-style or @number-style or @start-value or @mark-prefix or @mark-suffix or @item-sep or c:title]`

**Comment by kerwinso** [comment]
After deployment -- Baked content on qa to test: https://qa.cnx.org/contents/MBiUQmmY@18.55:y0GFmfab@6/11-Definitions-of-Statistics-P

"Raw" content on qa to test: https://qa.cnx.org/contents/y0GFmfab@6/Definitions-of-Statistics-Prob

**Pull request merged**
