### PR TITLE
Style figure titles correctly

### PR DESCRIPTION
**Pull request by caderitter**
Addresses [284 in cnx-recipes](https://github.com/Connexions/cnx-recipes/issues/284).

### CODE REVIEW

**Comment by caderitter** [comment]
@zroehr turns out there's also a problem with having no space between the title and caption content. Not sure if it's a webview or recipes issue. Some titles are correct, but some are not, so something is firing < 100%

**Comment by caderitter** [comment]
Further fix (adding the space after title) in recipes [#294](https://github.com/Connexions/cnx-recipes/pull/294)

**Comment by zroehr** [comment]
Are we waiting until the content is fixed to merge this?

**Comment by caderitter** [comment]
@zroehr I don't think so! I'll reassign to kerwin for testing

**Pull request merged**
