### PR TITLE
Change ost-iframe-embeddable to os-simulation

### PR DESCRIPTION
**Pull request by amberwebb**

### CODE REVIEW

**Comment by Dantemss** [comment]
You ok with this tag @philschatz? Can this be merged?

**Comment by philschatz** [comment]
Checking if the additional class is necessary.

**Comment by philschatz** [comment]
we use `os-embed` in other places. How about using `.ost-interactive .os-embed` as the `document.querySelector(...)` rather than defining a new class? That would match the videos a little closer as well

**Comment by Dantemss** [comment]
Should `ost-interactive` become `os-interactive` then?

**Comment by philschatz** [comment]
technically, probably yes. how much work would it be amanda? and the tagging-legend would need to be updated (kim/Alina)

**Comment by Dantemss** [comment]
According to Amber, the link should now have `.os-interactive .os-embed`.
Tutor still needs a class on the note and on the figure. My guess is that the note is `ost-interactive` and the figure is `.os-simfig` or something?

**Comment by philschatz** [comment]
Oh, I wonder if this opens up the `ost-reading-discard` discussion since the semantics is that Tutor should discard the element (but maybe look inside it for the `os-embed` element)

**Comment by amberwebb** [comment]
@philschatz Is this PR okay to merge with class names .os-interactive .os-embed?

**Comment by philschatz** [comment]
Yep, I think so :grimacing:. The rest is tutor-specific.

**Comment by Dantemss** [comment]
So you're ok with having both os-interactive and ost-interactive tags right Phil?

**Pull request merged**
