### PR TITLE
new logo

### PR DESCRIPTION
**Pull request by reedstrm**
we've got a new OS cnx logo.

### CODE REVIEW

**Comment by philschatz** [comment]
I noticed the old logo is transparent; should the new one be transparent as well?

**Comment by RoyEJohnson** [comment]
The old ones were different sizes; the new ones are the same size. Should there just be one copy and everything refers to it?

**Comment by reedstrm** [comment]
As my why there's a maintenance page w/  a separate logo? I don'r know.

**Comment by philschatz** [comment]
Also, should this file be a PNG? The other images in this repo are PNG, images for tutor are all PNGs, and the images for osweb are 50/50 PNG/JPG

/cc @edwoodward because it seems he might know how to find the source image for the logo 😄

**Comment by edwoodward** [comment]
I've requested a png with a transparent background.

**Comment by zroehr** [comment]
Does this new logo have the correct OS colors? The OS logo on the website has different colors. 
os-logo

**Comment by zroehr** [comment]
To clarify from previous comment. 
The new cnx logo:
logo-cnx

The os web logo:
os-logo

The colors seems to be off in the new cnx logo

**Comment by philschatz** [comment]
Thanks @zroehr ! That addressed my concerns. Any other concerns?

**Comment by reedstrm** [comment]
@phil you miss read @zroehr's  comment I think - we still don't have a correctly colored openstax cnx logo.

**Pull request merged**
