### PR TITLE
Fix for the IE 11

### PR DESCRIPTION
**Pull request by tomekstach**
### Webview
This pull request resolves bugs:
1. Website staging.cnx.org is not loading in IE 11.
2. Missing space at the bottom of the content where the license is displayed. You have to go to the 2nd page of a book to see it.

### l20n
We also sent a PR to the our version of l20n on the https://github.com/katalysteducation/l20n.js so you have to do `bower update` to get new version of l20n which contains fixes to use hyperlinks in the FTL code. This pull request resolves bugs:
1. License display should be a link to Creative Commons. The href is missing in the <a> tag

### CODE REVIEW

**Comment by tomekstach** [comment]
@philschatz Do I have to resolve these conflicts? I ask you because I don't want to do something wrong :)

I've just removed the Unicode bidi isolation characters from l20n. If you take the newest version of l20n from katalysteducation/l20n.js, it should works ok on IE11 and Edge.

**Comment by philschatz** [comment]
Yes please 🙏 .

Could the `browser-polyfill` package be included in the `main.js` file?

I remember @pandafulmanda did some work with reducing the number of `<script>` tags in the HTML so /cc'ing her for thoughts on

**Comment by tomekstach** [comment]
@philschatz, @pandafulmanda I think it might be doable. I think that only l20n cannot be included in the `main.js`. I will try to do that :)

**Comment by tomekstach** [comment]
@philschatz, @pandafulmanda I cannot move `browser-polyfill` to the `main.js`, because after that webview doesn't work properly on IE11 :(

**Comment by tomekstach** [comment]
@philschatz I think that everything is done from our site. You can merge these PR :)

**Comment by pandafulmanda** [comment]
thanks @tomekstach !

**Pull request merged**
