### PR TITLE
add selenium and test for l20n loading

### PR DESCRIPTION
**Pull request by philschatz**
This uses `chromedriver` and `--headless` with Selenium to test that `l20n` does in fact load and that it loads the Polish translation.

To see the multiple failed attempts at getting Travis to run properly, see the https://github.com/Connexions/webview/compare/pin-l20n branch

/cc @ludekarts, @tomekstach , & @reedstrm

### CODE REVIEW

**Comment by edwoodward** [comment]
@philschatz Is this still useful? If it is can you rebase so I can get it merged?

**Comment by philschatz** [comment]
@edwoodward I updated the PR and it runs locally. If it fails on travis I can change `./script/test` so that the Chrome test only runs locally (not on Travis)

**Comment by edwoodward** [comment]
@philschatz It is still failing on Travis.

**Comment by philschatz** [comment]
I disabled the test on Travis for now but it still runs locally.

**Comment by pumazi** [comment]
The `yarn.lock` file shouldn't have been committed. 😖

**Pull request merged**
