### PR TITLE
able to cancel search on modal close and clcking cancel using the query'...

### PR DESCRIPTION
**Pull request by pandafulmanda**
...s abort function and then emptying the results region view, #730

### CODE REVIEW

**Comment by amberwebb** [comment]
The search results are still coming up in the modal if I cancel after a successful search.

**Comment by pandafulmanda** [comment]
Okay, I guess I misunderstood this to only need to clear for when the search timeouts or when you cancel in the middle of the search.

So when someone hits cancel and there are search results, should it clear the results and the search text as well?

When someone hits the black modal overlay and that closes the modal, should that cause all the same actions as when you hit "Cancel" to close the modal?

Thanks!

**Comment by amberwebb** [comment]
The modal should clear when you cancel in the middle of a search. When  you reopen the modal, the progress bar should not show (which you have now) and the input field should be empty. If the modal is closed or canceled after a successful search, the results and input field should be empty as well. I don't think clicking on the overlay should close the modal, but that may be intended behavior with bootstrap modals? Not really sure about that, but it does happen with our other modals.

**Comment by pandafulmanda** [comment]
That is the default behavior with bootstrap modal.  I can change that setting for this modal, or do you think all modals on the webview should behave as such?

**Comment by amberwebb** [comment]
I don't know if they should or not. Make a separate issue for that and mark it as a question so we can address it as a team at a later time.

**Pull request merged**
