### PR TITLE
Added apple touch-icons

### PR DESCRIPTION
**Pull request by cburk**
Added apple touch-icons in order to fix the errors described here: 
https://github.com/Connexions/webview/issues/1205

### CODE REVIEW

**Comment by reedstrm** [comment]
Hmm, perhaps we should see what actual sizes are needed for apple-touch icons, rather than sending the same 64x64 to all requests.

**Comment by dak** [comment]
```
<link type="image/png" rel="apple-touch-icon-precomposed" href="/images/apple-touch-icon-57x57.png" sizes="57x57">
<link type="image/png" rel="apple-touch-icon-precomposed" href="/images/apple-touch-icon-76x76.png" sizes="76x76">
<link type="image/png" rel="apple-touch-icon-precomposed" href="/images/apple-touch-icon-120x120.png" sizes="120x120">
<link type="image/png" rel="apple-touch-icon-precomposed" href="/images/apple-touch-icon-152x152.png" sizes="152x152">
```

Somebody can doublecheck, but I don't think that's changed since the last time I looked into it.

**Comment by RoyEJohnson** [comment]
Is this ready to merge, or are we expecting updates for different sizes?

**Comment by dak** [comment]
I think it needs to be updated to have icons for the recommended sizes.

**Comment by edwoodward** [comment]
I  think we are waiting for Christian to update it. He will be back in Jan.

**Comment by cburk** [comment]
@dak as far as I can tell we only have a 64x64 image (src/images/cnx-64x64.png), is there an easy way to create these images at the correct sizes?  Could I use something like this:

http://www.superresize.me

to have one of each size?  Or is the issue that we need high quality images at each of these sizes?

**Comment by edwoodward** [comment]
You can install Gimp and scale the existing image.

**Comment by cburk** [comment]
Thanks ed, I'll do that

**Comment by dak** [comment]
@cburk I wouldn't recommend trying to scale the favicon up:
image
I don't think that's how we want people to see our logo.

I'd recommend starting with the actual logo (https://github.com/Connexions/webview/blob/master/src/images/logo.png), cropping it (that's what I originally did to make the favicon), and then scaling down.  There's an even higher res version of the logo available as well if you need it.

**Comment by cburk** [comment]
@dak sounds good, I'll try that

**Comment by cburk** [comment]
Hey guys,
So I did some basic testing, the relevant html appears in the header, but I'm not sure about how to test further or if that's possible.
Also, does anyone understand the error I'm getting?  I tried searching master and touch-icons for 2fc42bf and found nothing, and I checked for build-profile-with-oer.js and it exists and has read permissions.

**Comment by dak** [comment]
@cburk It looks like it was just a Travis CI error.  I restarted the build and it should pass this time.

**Comment by dak** [comment]
@cburk The favicons appear to be at the incorrect aspect ratio.  You'll probably want to have some whitespace above and below the icon.  My recommendation is to create an image with the correct aspect ratio and size, then paste the logo into that.

**Comment by dak** [comment]
@cburk on further review, you may need to rebase this and force push it.

**Comment by cburk** [comment]
Ok, thanks, I'll do that.

**Comment by edwoodward** [comment]
@dak I think this is ready to merge. Any problems lingering?

**Pull request closed without merging**
