### PR TITLE
update copy on about/contact

### PR DESCRIPTION
**Pull request by TomWoodward**
I used google translate for the polish....

image

### CODE REVIEW

**Comment by PiotrKozlowski** [comment]
```
about-contact-questions-content = Możesz skontaktować się z nami wysyłając e-mail na adres <a href="mailto:support@openstax.org">support@openstax.org</a>.
```
We are not sure if polish support have a different email address?

**Comment by openstaxalina** [comment]
@PiotrKozlowski you are correct - Support in Polish should have a different email address.  Do you have a support email address that you would like us to use?

**Comment by openstaxalina** [comment]
@TomWoodward To keep this moving forward, we should use `kontakt@openstax.pl` as the Polish support address.  Katalyst's project manager (who would have the final say) is currently out of office.  However, if she requests any changes, we will know before code freeze next week.  Please let me know if you have any concerns.

cc @PiotrKozlowski

**Comment by reedstrm** [comment]
@openstaxalina recall that this is a Through The Web (TTW) change, so doesn't _have_ to sync up with the release, but it can if we want to do it that way. I checked w/ Ed on what BIT does, he said they sync changes that are required for/related to new features, but that MARCOM makes other changes on their own schedule.

**Comment by openstaxalina** [comment]
@reedstrm Good reminder!  In fact we already released changes for other legacy pages (#1835) off-cycle this morning.  However, I am not comfortable directing traffic to `kontakt@openstax.pl` without Paulina's go-ahead.  As soon as I have word from her, I'll update here and we can proceed as quickly as Tom is available :-)

**Comment by openstaxalina** [comment]
@TomWoodward I got the go-ahead from Katalyst to use the email address - no changes needed. I suggest we could deploy to staging next week, I'll review, then we can deploy to prod.
cc @reedstrm @kerwinso

**Pull request merged**
