### PR TITLE
Add Jump to Concept Coach button

### PR DESCRIPTION
**Pull request by dak**
Screenshot

### CODE REVIEW

**Comment by philschatz** [comment]
Can you include a screenshot in the PR body? That helps UX (& QA) have a way to verify and/or discuss the changes

**Comment by philschatz** [comment]
Why not just make the "Jump to Concept Coach" a link, and add an `id='concept-coach'` to the SVG image on the bottom of the page?

**Comment by dak** [comment]
There's 2 issues with the link only suggestion:

1) From the story: `Behavior of button is the same as the “Launch Concept Coach” button at the bottom of the reading.`. That to me suggests the button needs to actually launch concept coach, not just move the user to it on the screen.

2) It is explicitly stated it needs to be functional on intro pages too, which don't have the concept coach widget on them (so the SVG image doesn't exist on the page to jump to).

**Comment by dak** [comment]
Screenshot

**Comment by philschatz** [comment]
oh, I might have misunderstood the ticket & thought it was meant to scroll down; but I agree, if the intro modules don't have any exercises I'm not sure what does/should happen in that case. /cc @jason-holmes @Fredasaurus @rvnewell (`@openstax/ux`)

**Comment by jason-holmes** [comment]
We had originally intended the big button at the top to launch CC directly, but that behavior was later changed to scroll down the page to the launcher area instead...sorry the documentation wasn't updated.  The correct behavior for that top button is to scroll down the page to the launcher graphic.

Re: what to do with page modules in CC books that don't have questions (eg, Introductions).  I just discussed this with Kim...for now, we'd like to remove both the big top button AND the launcher from these pages.

**Comment by dak** [comment]
@jason-holmes For pages in CC books without the launcher (Introductions), should the "Get This Book" button still be visible, or should no button be visible there at all (no 'Jump To CC' or 'Get This Book button').

**Comment by jason-holmes** [comment]
“Get this book” button should NOT be visible for CC books.

**Pull request merged**
