### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by BryanEliDimas**
- Fixed: use `nvm` instead of `n`. Wasn't updated here: https://github.com/Connexions/webview/commit/859ec4d4773372e24d596531d86eeb203a64effd
- Other minor fixes.

### CODE REVIEW

**Comment by Dantemss** [comment]
Looks good to me, but I think @philschatz should look, he has more experience with node/js installs.

**Comment by philschatz** [comment]
Thanks for submitting this fix! 

For most of the repositories we have switched to using [nodenv](https://github.com/nodenv/nodenv) and use the scripts in http://github.com/openstax/setup-scripts .

Could you try copy/pasting the `/script/bootstrap` and `/script/setup` from that repository and see if things still install properly?

**Comment by BryanEliDimas** [comment]
@philschatz No problem! Things _seemed_ to install properly, but my tests are still not running all properly. The phantomjs tests get stuck doing apparently nothing:
```
Running "mocha" task

Running "mocha:browser" (mocha) task
Verifying property mocha.browser exists in config...OK
Files: test/index.html -> browser
Options: log=false, reporter="Spec", timeout=15000, inject="/Users/bryaneli/openstax/webview/node_modules/grunt-mocha/phantomjs/bridge.js", phantomScript="/Users/bryaneli/openstax/webview/node_modules/grunt-mocha/phantomjs/main.js", urls=[], bail=false, logErrors=false, growlOnSuccess, run=false
Options: {
  "log": false,
  "reporter": "Spec",
  "timeout": 15000,
  "inject": "/Users/bryaneli/openstax/webview/node_modules/grunt-mocha/phantomjs/bridge.js",
  "phantomScript": "/Users/bryaneli/openstax/webview/node_modules/grunt-mocha/phantomjs/main.js",
  "urls": [],
  "bail": false,
  "logErrors": false,
  "growlOnSuccess": true,
  "run": false
}
Phantom options: {
  "timeout": 15000,
  "inject": "/Users/bryaneli/openstax/webview/node_modules/grunt-mocha/phantomjs/bridge.js",
  "phantomScript": "/Users/bryaneli/openstax/webview/node_modules/grunt-mocha/phantomjs/main.js",
  "logErrors": false,
  "growlOnSuccess": true,
  "run": false
}
Testing: test/index.html
```

**Comment by Dantemss** [comment]
Helped him fix it, tests are running now.

**Comment by BryanEliDimas** [comment]
@philschatz Updated setup scripts and updated readme accordingly.

**Pull request merged**
