### PR TITLE
Wait to load book count

### PR DESCRIPTION
**Pull request by sisiz**
Waiting to load the text of the book count until the count has actually been loaded.
Also adding special case text for if there are 0 or 1 books found.
(example page in one book. not sure where to find one in 0 books to look at http://localhost:8000/contents/e6qfF73c@3/131-Chromosomal-Basis-of-Inher)

(https://github.com/Connexions/webview/issues/1620)

### CODE REVIEW

**Comment by reedstrm** [comment]
So, we need some code that watches the appropriate model, so that the booklist is opened once it's loaded.

**Comment by sisiz** [comment]
sorry, what is the issue? When the data-l10n-* args replace the span with the translated text why would it not be correct?

**Comment by reedstrm** [comment]
Just figured it out - the default text that was in the template would render _before_ the model loaded, that's where the "This page is in  books" flash was coming from. The simplest fix is to just not have any default text, depend on l20n to load the text from the dictionary.ftl file

**Comment by reedstrm** [comment]
Tested locally, this _does_ also solve the problem, since the numBooksText resolves to [empty string] until extras is loaded. I think we'll merge this, since it gives us the code to consider other solutions in the future.

**Pull request merged**
