### PR TITLE
Removing extra content stack from history when navigating to a book

### PR DESCRIPTION
**Pull request by amberwebb**
Fixes https://github.com/Connexions/webview/issues/882

### CODE REVIEW

**Comment by dak** [comment]
This seems like it's curing the symptom instead of the problem.

**Comment by amberwebb** [comment]
Yes, but I am unable to find the root of the problem.

**Comment by dak** [comment]
If the url duplication is happening when the url is changed to include the version and page number, then that's where the problem is.  It may just need an `options.replace = true` to make sure it replaces the url instead of adding a new one.

**Comment by amberwebb** [comment]
That's actually what I've been looking for. This is happening after media view loads. What loads after media view?

**Comment by amberwebb** [comment]
So I found the proper place to add options.replace. It's buried in media/tabs, which is the one place I did not look yesterday.

**Pull request merged**
