### PR TITLE
Upgrade deps

### PR DESCRIPTION
**Pull request by philschatz**
I skipped `grunt` and `grunt-mocha` because those required non-trivial changes.

Also, I was thinking of adding https://greenkeeper.io to this repo. Objections? It will result in PR's like: https://github.com/philschatz/octokat.js/pulls

### CODE REVIEW

**Comment by philschatz** [comment]
Reminder: When this is approved, give QA instructions on how to deploy+test (likely just deploy to QA and spot-check the CSS styling)

**Comment by philschatz** [comment]
Just deploy this sha to QA.

The minimum set of things to test would be:

- [ ] verify the homepage looks the same as before

Optional things to check:

- [ ] look at a piece of content (that contains Math and a figure) in a book
- [ ] click next/prev and verify the correct piece of content shows up
- [ ] search for a term and click on a result
- [ ] verify that all 4 of those pages are styled the same

**Comment by reedstrm** [comment]
:+1: on greenkeeper - automation for this sort of thing is good.

**Comment by philschatz** [comment]
ah, the joys of rebasing. I think Jenkins is reporting "No changes" because it already built this commit.

I pushed a new commit and then removed it because it caused travis to fail. I'll push a new commit to verify my theory.

**Comment by karenc** [comment]
I wish Jenkins is less clever about these kind of things :p

**Comment by kerwinso** [comment]
verified on qa.cnx.org

**Pull request merged**
