### PR TITLE
adds source maps

### LINKED ISSUE #1378: Add sourcemaps to all builds (including production)
This would allow the dev instance to run much faster and allow debugging on production.

The code is already open-source and the _only_ overhead is a 10-character comment at the end of the minified JS file.

Plus, it could help get people on the internet to fix bugs or maybe learn some coding :smile:

related: openstax/tutor-js#916

### PR DESCRIPTION
**Pull request by philschatz**
image

The files load but I am not sure about the best places to set breakpoints to verify. Also, I did not look very hard to see if `requirejs` could include the original `.coffee` source (see screenshot)

Fixes #1378

### CODE REVIEW

**Comment by reedstrm** [comment]
What does this screenshot demonstrate?

**Comment by philschatz** [comment]
It shows that rather than showing the mangled (minified) Javascript, the source mapping document is loaded. The grey background on some lines means you can no longer break on that line (probably because the mangling reordered some statements or something)

**Comment by reedstrm** [comment]
Ah, so we'd switch dev to run in a minified mode - right  forgot that step.

**Comment by philschatz** [comment]
Yep, that makes dev run more like production, and the source maps should also be on production. I think someone (maybe @dak or @RoyEJohnson ) might want to verify the source code actually still lines up (by setting breakpoints and stepping through or something)

**Comment by RoyEJohnson** [comment]
I've set a few breakpoints and they behave as expected.

**Comment by philschatz** [comment]
:sparkles: Yay! :sparkles: should I post somewhere on the deployment-side of things to also run minified for `dev`?

**Pull request merged**
