### PR TITLE
Hide "Skip to Main Content" using opacity CSS

### PR DESCRIPTION
**Pull request by RoyEJohnson**
Update CSS to set opacity to 0 when not in focus

### CODE REVIEW

**Comment by dak** [comment]
Have you checked if you're able to tag-focus into an item with 0 opacity in every browser?

**Comment by RoyEJohnson** [comment]
I have checked in the sense of looking it up (opacity does not affect tab
order), but I haven't done testing in multiple browsers.

On Wed, Sep 9, 2015 at 2:07 PM, Derek Kent <notifications@github.com> wrote:

> Have you checked if you're able to tag-focus into an item with 0 opacity
> in every browser?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Connexions/webview/pull/1176#issuecomment-139013650>.
>



-- 
Roy Johnson
Javascript Developer
OpenStaxx

**Comment by philschatz** [comment]
For what it's worth Github does it by:

```html
<body>
  <a href="#start-of-content" tabindex="1" class="accessibility-aid">Skip to content</a>
  ...
```

```css
.accessibility-aid {
  height: 1px;
  width: 1px;
  clip: rect(1px, 1px, 1px, 1px);
  overflow: hidden;
  position: absolute;
  margin: 0;
}
```

**Comment by RoyEJohnson** [comment]
Github's solution works on Github, but I can't see from observing the CSS what changes when it gets focus. I plugged their CSS into our page, but tabbing to the link didn't cause it to be visible.

**Comment by philschatz** [comment]
The `:focus` selector does the work:

```css
.accessibility-aid:focus {
  height: auto;
  width: auto;
  clip: auto;
  z-index: 1;
  top: 0;
  line-height: 49px;
  padding: 0 10px;
  background: #f5f5f5;
  font-weight: bold;
  text-decoration: none;
  color: #333;
}
```

**Comment by RoyEJohnson** [comment]
I'm just surprised that Chrome debugger didn't show anything changing.

Is this the solution we want to use? I can plug it in in the morning.

On Wed, Sep 9, 2015 at 6:55 PM, Philip Schatz <notifications@github.com>
wrote:

> The :focus selector does the work:
>
> .accessibility-aid:focus {
>   height: auto;
>   width: auto;
>   clip: auto;
>   z-index: 1;
>   top: 0;
>   line-height: 49px;
>   padding: 0 10px;
>   background: #f5f5f5;
>   font-weight: bold;
>   text-decoration: none;
>   color: #333;
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Connexions/webview/pull/1176#issuecomment-139075792>.
>



-- 
Roy Johnson
Javascript Developer
OpenStaxx

**Comment by edwoodward** [comment]
Let's discuss in scrum.

**Comment by RoyEJohnson** [comment]
Verified that the Skip to Main and Skip to Results work as expected on the search page.

**Comment by edwoodward** [comment]
Great. I'll verify in IE once it is on dev.

**Comment by amberwebb** [comment]
I must have missed a conversation in scrum. Why use opacity instead of negative margin?

**Comment by RoyEJohnson** [comment]
On large displays, the hidden item shows up onscreen.

**Pull request merged**
